### ISSUE TITLE
file limitation on online interface compared to command line usage

### ISSUE THREAD

**Issue by tramyn** [jamesscottbrown/sbml-diff#10]
Online interface limit to 3 files to diff. while command line allows more than 3 . I’ve tested up to 6 models on command line but message isn’t clear on result of 6 models that were inputted to diff. I wasn’t able to output optional arguments (i.e. –params and –kinetics) for the 6 models to compare the results.

**Comment by jamesscottbrown** [comment]
> Online interface limit to 3 files to diff. while command line allows more than 3 

I'll extend the online interface to an arbitrary number of files.

> I’ve tested up to 6 models on command line but message isn’t clear on result of 6 models that were inputted to diff

What do you mean by message? Do you mean that the resulting diagram is confusing (comparing many things at once is difficult)?

> I wasn’t able to output optional arguments (i.e. –params and –kinetics) for the 6 models to compare the results.

A command like that you gave in Issue #2 should work. On my machine this works:

`~/Downloads/test_files/ $ sbml-diff.py  --params --kinetics  assignmentRuleModel.xml modifiedKineticLaw.xml modifiedParameter.xml modifiedIdModel.xml modifiedParameterValue.xml modifiedSBOTermModel.xml`

**Comment by tramyn** [comment]
@jamesscottbrown : I was referring to the two tables which was addressed in #2 . This is now working. Thanks!
