### ISSUE TITLE
broken dot file after performing diff on multiple SBML files with optional arguments 

### ISSUE THREAD

**Issue by tramyn** [jamesscottbrown/sbml-diff#2]
Running this command WITH optional arguments doesn’t allow me to view the output dot file:  
python sbml-diff.py --params --kinetics --outfile result2.dot /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/assignmentRuleModel.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedKineticLaw.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedParameter.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedIdModel.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedParameterValue.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedSBOTermModel.xml 

However, running this command WITHOUT optional arguments will generate a working dot file to view:  
python sbml-diff.py --outfile result2.dot /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/assignmentRuleModel.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedKineticLaw.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedParameter.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedIdModel.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedParameterValue.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/modifiedSBOTermModel.xml

**Comment by jamesscottbrown** [comment]
What's going on here is that when `--params` or `--kinetics` are specified, sbml-diff assumes you only want the corresponding tables, not the DOT output. The rationale for this is that you probably want to process DOT output and tables separately, so it makes sense to request them with separate invocations of the sbml-diff.

The`--outfile` option redirects all output to the specified file. So your first command doesn't produce a DOT file at all - it produces a text file containing the two tables [or one table, before issue #1 was resolved].

**Comment by tramyn** [comment]
@jamesscottbrown perfect! I am getting the two tables just as you described.
