### ISSUE TITLE
README.md instructions for example test files

### ISSUE THREAD

**Issue by tramyn** [jamesscottbrown/sbml-diff#6]
It would be nice to provide an example command line with example diff files for user to run as tutorial to ensure all setup is working correctly (i.e. python sbml-diff.py --outfile result.dot /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/entireStructure.xml /Users/tramynguyen/Documents/GSoC_2016/sbml-diff/test/subStructure.xml)

**Comment by jamesscottbrown** [comment]
Would you be happy for me to distribute some of the test files that you emailed to me?

**Comment by tramyn** [comment]
Hi @jamesscottbrown , feel free to distribute the models if you like. I have no objections to this.
